apiVersion: v1
kind: Service
metadata:
  name: doesgoogleexecutejavascript
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: doesgoogleexecutejavascript
  type: LoadBalancer
